application: madmax-chat-email
version: 1
runtime: python
api_version: 1

handlers:
- url: /.*
  script: pchat.py
- url: /_ah/mail/.+ 
  script: handle_incoming_email.py 
  login: admin
  
inbound_services:
- mail